### ISSUE TITLE
vascaling now removed from oggm core

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-vas#2]
https://github.com/OGGM/oggm/pull/1065

it might be worth checking if everything is still working on this side -> possibly BASENAMES has to be updated in this code since it has been removed from oggm.cfg

**Comment by oberrauch** [comment]
Yes... and probably the scaling parameters as well! What about creating a "oggm_vas.cfg"?! It could have its own initialize() which is called after the oggm's and adds the needed values to cfg.PARAMS?!

**Comment by oberrauch** [comment]
But the [`vas_ref_tstars.csv` files](https://github.com/OGGM/oggm-sample-data/pull/4) may stay in the oggm-sample-data repository?! Or should I move the into this repo as well? And add a VAS `get_demo_file()`?

**Comment by fmaussion** [comment]
Yes right I forgot about these: https://github.com/OGGM/oggm/pull/1066

1. Having your own oggm-vas.initialize() routine is a good idea, it does not need to be as fancy as OGGM's though. You can simply initialize OGGM and then add your parameters to oggm's PARAMS at runtime with:

```python
from oggm import cfg
cfg.initialize()
cfg.PARAMS['vas_c_area_m2'] = 0.191
```

Here are the lines I removed from OGGM:

```
### VAS model params
# area-volume scaling parameters for glaciers (cp. Marzeion et. al., 2012)
# units: m^(3-2*gamma) and unitless, respectively
vas_c_area_m2 = 0.191
vas_gamma_area = 1.375

# area-length scaling parameters for glaciers (cp. Marzeion et. al., 2012)
# units: m^(3-q) and unitless, respectively
vas_c_length_m = 4.5507
vas_q_length = 2.2

# TODO: include scaling parameters for ice caps?!
```

2. For the removed BASENAMES, add this to your VAS initialize() routine:

```python
from oggm import cfg
cfg.initialize()
_doc = ("A dict containing the glacier's t*, bias, mu*. Analogous "
        "to 'local_mustar.json', but for the volume/area scaling model.")
cfg.add_to_basenames('vascaling_mustar', ('vascaling_mustar.json', docstr=_doc)
```

3. For the params files, I also removed them from the oggm-sample data dir.  This a bit more annoying for you, but also consistent with the "separation of concerns". Somewhere in your calibration step you should have some code which puts the file in the working directory -> this has to be adapted with new file paths. I'll make a PR shortly to add the removed files to the package.

**Comment by oberrauch** [comment]
Hey @fmaussion, I ran into the following two problems:

1. `__init__.py` throws an error when it tries to import `local_t_star`. The `entity_task` decorator gets hung up on the fact, that `vascaling_mustar` is not (yet) a basename. Should I run the vas initialize() in the `__init__.py` file first?!

2. All tests fail since the `oggm.pytest_plugin` module is removed. I'm sure that is an easy fix, however I couldn't do it myself.

Thanks already!

**Comment by fmaussion** [comment]
For 1, the solution is in my post above. 

I'm not sure to understand 2. Can you be more specific?

**Comment by oberrauch** [comment]
I think I implemented the suggestions from your post above correctly. The error occurs at `impot oggm_vas`... it imports `local_t_star()` and the decorator tries to write to `vascaling_mustar` but it is not a basename yet, since `oggm_vas.initialize()` cannot be called before importing it... Or do I miss something here...?!

**Comment by fmaussion** [comment]
Yes sorry 

`cfg.add_to_basenames` can be run without cfg.inialize. the first lines of code in `__init__` should be:

     
```
from oggm import cfg
_doc = ("A dict containing the glacier's t*, bias, mu*. Analogous "
        "to 'local_mustar.json', but for the volume/area scaling model.")
cfg.add_to_basenames('vascaling_mustar', ('vascaling_mustar.json', docstr=_doc)

... vas stuff ...
```

**Comment by oberrauch** [comment]
Ok, thanks. I thought it should be something along those lines, but couldn't figure it out myself.
For the problem with the tests, the [OGGM pull #1062](https://github.com/OGGM/oggm/pull/1062) removed `'pytest11': ['pytest_oggm = oggm.pytest_plugin']`, as entry point in the setup file. If I run tests I get the following error `ModuleNotFoundError: No module named 'oggm.pytest_plugin'`. As I said, I guess it is an fix... but I don't really know where to look.

**Comment by fmaussion** [comment]
can you send the full traceback? Otherwise try to deinstall OGGM from your env, then install the latest version again

**Comment by fmaussion** [comment]
I wonder where this error happens

**Comment by oberrauch** [comment]
Ok, so no easy fix 😅  Yeah I'll try to reinstall it and if the error persists, I'll get back to you.
But the rest works for now... Thanks so far!

**Comment by fmaussion** [comment]
if it persists please send the full traceback

(this holds true for all possible errors. Without traceback it's barely impossible to know what's going on)
